language: node_js
node_js:
    - 8
    - 10
addons:
    chrome: stable
cache:
    yarn: true
    directories:
        - node_modules
branches:
    only:
        - master
script:
    - npm run-script build
    - npm run-script unit:travis
